name: Update translation, readme and debian/control in main branch automatically
on:
  push:
    branches:
      - main
    paths-ignore:
      - po/*
      - README.md
      - debian/control

env:
  apt_dependencies: >-
    ca-certificates curl dconf-cli gcc gettext git libnss-wrapper libsmbclient-dev
    libwbclient-dev pkg-config protobuf-compiler python3-coverage samba sudo

jobs:
  update-po:
    name: Update po files
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y gettext
      # Checkout code with git
      - uses: actions/checkout@v3
        with:
          ref: main
      # Install go
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      # Update po if needed
      - name: Check po files
        id: checkpo
        run: |
          set -eu

          hasModif="false"
          go generate ./internal/i18n/
          # Exclude line diffs only
          MODIFIED=$(git difftool -y -x "diff -Nup -I '^#: '" po/)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update po files
          title: Auto update po files
          labels: po, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-po
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-po:main

  update-readme-clid-ref:
    name: Update readme and CLI ref files
    # This should just be "after", but we don't want the 2 jobs to push at the same time
    needs: update-po
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y ${{ env.apt_dependencies }}
      # Checkout code with git
      - uses: actions/checkout@v3
        with:
          ref: main
      # Install go
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      # Try updating README
      - name: Check README file
        id: checkreadme
        run: |
          set -eu

          hasModif="false"
          cd cmd/adsysd
          go run ../generate_completion_documentation.go update-readme
          go run ../generate_completion_documentation.go update-doc-cli-ref
          MODIFIED=$(git status --porcelain --untracked-files=no)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update readme files
          title: Auto update readme files
          labels: readme, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-readme-cli-ref
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-readme-cli-ref:main

  update-rust-vendored-sources:
    name: Update XS-Vendored-Sources-Rust on debian/control
    needs: update-readme-clid-ref
    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
    steps:
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cargo dh-cargo git
      - uses: actions/checkout@v3
      - name: Vendoring the dependencies
        run: |
          cargo vendor vendor_rust/
      - name: Update XS-Vendored-Sources-Rust
        run: |
          set -eu

          export CARGO_VENDOR_DIR=vendor_rust/
          VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources 2>&1 || true)
          OUTPUT=$(echo "$VENDORED_SOURCES" | grep ^XS-Vendored-Sources-Rust: || true)
          if [ -z "$OUTPUT" ]; then
            exit 0
          fi
          sed -i "s/^XS-Vendored-Sources-Rust:.*/$OUTPUT/" debian/control

          echo "modified=true" >> $GITHUB_ENV
        shell: bash

      - name: work around permission issue with git vulnerability (we are local here). TO REMOVE
        run: git config --global --add safe.directory /__w/adsys/adsys

      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        # V5 Beta needed because of https://github.com/peter-evans/create-pull-request/issues/1170
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update Rust vendored sources in debian/control
          title: Auto update Rust vendored sources in debian/control
          labels: control, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-rust-vendored-sources
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-rust-vendored-sources:main

  update-fake-checksum-file:
    name: 'Update the fake checksum file at d/cargo-checksum.json'
    needs: update-rust-vendored-sources
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y git nodejs
      - uses: actions/checkout@v3
      - name: 'Install GitHub script dependencies'
        run: npm install -D toml @types/node
      - name: 'Update the checksum file'
        uses: actions/github-script@v6
        id: update-checksum
        with:
          script: |
            const toml = require("toml");
            const fs = require("fs");
            const checksum_path = "./debian/cargo-checksum.json";
            /** @typedef LockEntry @prop {string} name @prop {string} checksum @prop {string} version */
            /** Read and parse the lock file
            * @param {string} path
            * @returns {any} */
            function readLock(path) {
              const lock = fs.readFileSync(path, { encoding: "utf-8" });
              return toml.parse(lock);
            }

            const lockfile = readLock("./Cargo.lock");
            /** @type {LockEntry?} */ const sd_block = lockfile.package.find(
              (/** @type {LockEntry} */ x) => x.name === "system-deps"
            );
            if (!sd_block) throw new Error("system-deps not found in the lock file");
            const old_cksum_file = require(checksum_path);
            if (old_cksum_file.package === sd_block.checksum) {
                console.info("Checksum is up-to-date. No update needed.");
                return false;
            }
            const new_cksum_file =
              JSON.stringify({
                package: sd_block.checksum,
                files: {},
              }) + "\n";
            fs.writeFileSync(checksum_path, new_cksum_file);
            console.info("Checksum file updated.");
            return true;
      - name: Create Pull Request
        if: ${{ steps.update-checksum.outputs.result == 'true' }}
        # V5 Beta needed because of https://github.com/peter-evans/create-pull-request/issues/1170
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update Rust vendored sources checksums
          title: Auto update Rust vendored sources checksums
          labels: control, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-rust-checksum
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ steps.update-checksum.outputs.result == 'true' }}
        run: |
          git push origin auto-update-rust-checksum:main
